package com.example.adminbusapp.objects

object busStandData {

    val arr = mapOf(
        "165" to arrayOf(
            "Stop Names",
            "Anand Vihar ISBT",
            "Ram Prastha",
            "Ram Prastha Temple",
            "Surya Nagar",
            "Shahdra Border",
            "Jhilmil X-Ing",
            "Dilshad Garden GT Road",
            "Dilshad Garden School",
            "GTB Hospital",
            "GTB Hospital X-Ing",
            "GTB Hospital X-Ing",
            "Nand Nagri Terminal",
            "Nand Nagari E-Block",
            "Gagan Cinema",
            "Gagan Cinema",
            "Bank Colony",
            "Mandoli Chungi",
            "Ashok Nagar",
            "MIG Flats Loni Road",
            "Loni Road X-Ing",
            "Yamuna Vihar C-4 Block",
            "Yamuna Vihar Brijpuri",
            "Yamuna Vihar Block C-1",
            "Bhajan Pura",
            "Khajoori Khas",
            "Rajiv Vihar",
            "Nanak Sar",
            "Wazirabad Bridge",
            "Jagatpur X-Ing",
            "Gandhi Vihar",
            "Burari X-ing",
            "Mukund Pur X-ing",
            "Jahanhgir Puri X-ing",
            "Bhalaswa X-ing",
            "Outer Ring Road Makbara Chowk",
            "GTK By Pass",
            "Sanjay Ghandhi Transport Nagar",
            "Samay Pur",
            "Badli Railway Staion",
            "Rohini Sector-18",
            "Rohini Sector-16",
            "Rohini Sector-16 X-Ing",
            "Delhi Engineering College",
            "Shahbad Daulat Pur",
            "St Micle School"
        ),
        "317" to arrayOf(
            "Stop Names",
            "Shivaji Stadium Terminal",
            "Super Bazar",
            "Govt Press",
            "DDU Marg",
            "Govt Sr.Sec. School",
            "Bal Bhawan",
            "ITO",
            "Delhi Secretarait",
            "Rainy Well",
            "Ramesh Park",
            "Bank Enclave",
            "Sahstri Nagar Pushta",
            "Laji enclave",
            "Chacha Nehru Hospital",
            "Gurudwara Jheel Colony",
            "Jheel Dispensary",
            "Jheel Terminal",
            "Lala Quarter",
            "Krishna Nagar",
            "Azad Nagar Mod",
            "Jharkhandi",
            "Kanti Nagar",
            "Shyam Lal College"
        ),
        "374" to arrayOf(
            "Stop Names",
            "Nand Nagari Terminal",
            "GTB X-ing",
            "Nand Nagari C Block",
            "Jagat Puri",
            "Durga Puri",
            "Jyoti Colony",
            "Durga Puri",
            "Babar Pur",
            "Mog Pur Crossing",
            "Zafrabad School",
            "Selam Pur",
            "Welcome Colony",
            "Kanti Nagar",
            "Jharkhandi",
            "Azad Nagar",
            "Swarn Cinema",
            "Krishna Nagar",
            "Hans Apartment",
            "Arjun Nagar",
            "Radhe Puri",
            "Jagat Puri A Block",
            "Jagat Puri F Block",
            "KK X-ing",
            "New Rajdhani State",
            "Sawath Vihar",
            "Nirman Vihar",
            "Shankar Mode",
            "Shakarpur",
            "Lakshmi Nagar",
            "Rainy Well",
            "Delhi Secretiriat",
            "IP Power Station",
            "IP Depot",
            "Railway X-ing",
            "Pargati Madain",
            "National Stadium",
            "Zoo",
            "Sunder Nagar",
            "DPS School",
            "Obrai Hotel",
            "Lodhi Hoetl",
            "Panth Nagar",
            "Deffence Colony",
            "Mool Chand Hospital",
            "Central School",
            "LSR College",
            "Kailash Colony",
            "Sant Nagar",
            "Nehru Place",
            "Paras Cinema"
        ),
        "969" to arrayOf(
            "Stop Names",
            "NARELA",
            "MCD Primary School Mandi Narela",
            "NARELA MANDI",
            "RLY XING NARELA",
            "Vishal Bagh",
            "Swatantra Nagar",
            "Bharat Mata Public School",
            "SANOTH XING",
            "GHOGA AIRFORCE STN.",
            "Bawana",
            "BAWANA SCHOOL",
            "Industrial Area Bawana",
            "Maharshi Balmiki Government Hospital",
            "POOTH KHURD",
            "ASTHAL POOTH",
            "Barwala",
            "BARWALA PATHSHALA",
            "Prahlad Pur",
            "PREHLAD PUR SCHOOL",
            "Shahbad Dairy",
            "Shahbad Dairy Terminal",
            "Shahbad Dairy",
            "ST. MICLE SCHOOL",
            "SHAHBAD DAULAT PUR",
            "ENG. COLLEGE",
            "Rohoni Sector 16",
            "ROHINI SEC-15.16 XING",
            "Rohoni Sector 11",
            "ROHINI SECT-D-2",
            "VIDYA VIHAR MARG XING",
            "Rohini Sector-7 & 8 X-Ing",
            "Fire Station Sector-8",
            "Madhuvan Chowk",
            "Madhuvan Chowk",
            "SARSWATI VIAHR C-BLOCK",
            "Dipali Chowk",
            "kali Mandir",
            "Pushpanjali",
            "Rohini Depot III",
            "MANGOL PUR SCHOOL",
            "West Enclave",
            "MANGOL PURI B- BLK",
            "Peera Garhi Chowk",
            "Peera Garhi Depot",
            "POWER HOUSE",
            "RBI Colony",
            "Sundar Vihar",
            "Meera Bagh",
            "Meera Bagh Appartment",
            "KESHO PUR DEPOT",
            "MJR. BHUPENDER SINGH NGR",
            "CRPF Camp",
            "KRISHANA PURI",
            "Kangra Niketan",
            "District Centre",
            "Dholi Piao",
            "VIKAS PURI XING"
        ),
        "GL-23" to arrayOf(
            "Stop Names",
            "ISBT Maharana Pratap Bus (T)",
            "ISBT Kashmiri Gate",
            "Shyam Giri Mandir",
            "Shastri Park",
            "Dharam Pura",
            "Seelam Pur",
            "Welcome",
            "Kanti Nagar",
            "East Azad Nagar",
            "Swarn Cinema",
            "East Krishna Nagar",
            "Hans Appartment",
            "Arjun Nagar",
            "Radhey Puri",
            "Jagatpuri A-Block",
            "Jagatpuri F-Block",
            "Hasanpur Depot",
            "Hasanpur Village",
            "Gazipur Depot"
        )
    )

}